### ISSUE TITLE
Error with Input 

### ISSUE THREAD

**Issue by noor-albader** [BCH-RC/DiVenn#1]
I created tab-delimitated expression data following the data input guidelines  and the first example in the tutorial. 
I get this following error:
Notice: Undefined offset: 0 in /var/www/html/showdata.php on line 28

The number of errors depends on the number experiments. With 2 experiments, I get one error and with 4, I get two errors. 

I have attached two files I have tried to use on the app. 

[Exp_0_DiVenn_Input.txt](https://github.com/noble-research-institute/DiVenn/files/2853670/Exp_0_DiVenn_Input.txt)
[Exp1_DiVenn_Input.txt](https://github.com/noble-research-institute/DiVenn/files/2853671/Exp1_DiVenn_Input.txt)

**Comment by sunliang3361** [comment]
You have to remove all duplicate gene IDs from your input list. I just tried to remove all duplicate IDs and their corresponding expression values from Exp_0_DiVenn_Input.txt. It works fine from my side.

**Comment by noor-albader** [comment]
That worked! I removed duplicated IDs from input list and did not get any other errors.
