### ISSUE TITLE
microarray data doesn't work

### ISSUE THREAD

**Issue by sunliang3361** [BCH-RC/DiVenn#4]
DiVenn doesn't work for microarray data? Just because it contains "_" in the probe IDs?
my sample data is below:

1556499_s_at	1
202289_s_at	1
211382_s_at	1
210746_s_at	1
229309_at	1
227236_at	1
205532_s_at	1
204083_s_at	1
238197_at	1
201289_at	1
231798_at	1
236421_at	1
237597_at	1
205590_at	1
206726_at	1
229121_at	1
201438_at	1
205495_s_at	1

**Comment by yinbingge** [comment]
Yes, It was a problem if the GeneId is started with a number. We fixed it. Please try it again

**Comment by sunliang3361** [comment]
Thanks, still not working?

**Comment by yinbingge** [comment]
This issue occurred because the input is delimited by space instead of tab space. Now Divenn works with both space and tab space.
