### ISSUE TITLE
summarize node group function 

### ISSUE THREAD

**Issue by sunliang3361** [BCH-RC/DiVenn#5]
I like the "summarize node group function", but somehow it's not correct?
<img width="736" alt="Screen Shot 2020-07-30 at 9 17 19 PM" src="https://user-images.githubusercontent.com/8751391/88989813-7c4e4900-d2aa-11ea-9545-114ccf85e16a.png">

There are unique genes for both exp0 and exp 1 in the graph above, but after I summarized node group, DiVenn generated the graph below which is a great function but not 100% correct, it seems there is no unique gene for exp0 anymore. thank you for the great upgrading job.

<img width="678" alt="Screen Shot 2020-07-30 at 9 16 56 PM" src="https://user-images.githubusercontent.com/8751391/88989930-c1727b00-d2aa-11ea-8e46-44b96a4db6cd.png">

**Comment by yinbingge** [comment]
This issue is solved
