### ISSUE TITLE
From annotation to DiVenn

### ISSUE THREAD

**Issue by mictadlo** [BCH-RC/DiVenn#7]
Hi,
We have annotations for two plants, however, one is the wild type. Each annotation contains in Note an ID from the NR database.

Does DiVenn require a gene id and how often it occurs?

Thank you in advance,

Best wishes

Michal

**Comment by mictadlo** [comment]
P.S. How would you extract the data from GFF3 file to DiVenn?

**Comment by yinbingge** [comment]
The DiVenn need at least two columns. The first column is gene and second column is expression values ( for example, “1” represents up regulated gene, “2” represents downregulated gene). We added a new feature to allow users to input user's own annotation in the version 2. Each column is separated by tab space. Any column except for Col 1 and 2 can be replaced by a “-” if you don’t have corresponding information. Col 1 can be any nickname without special characters.   

Col 1: ID               
Col 2: expression value  
Col 3: UniprotD ID            
Col 4: NCBI ID     
Col 5: Description             
Col 6: Pathway  
Col 7: GO ID        
Col 8: GO term  
Col 9: GO category           
Col 10: P Value


You can prepare these columns Data in the excel and copy the data from excel and paste it to our website. Please read this tutorial at https://github.com/noble-research-institute/DiVenn, there is a video you can watch in the link.
